### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by charlysan** [lestrrat-go/apache-logformat#22]
Is there a way to easily add custom fields to the [log string](https://github.com/lestrrat-go/apache-logformat/blob/master/interface.go#L18). I would like to add the name of the service, so that I could easily filter between different services from kibana. E.g.

```
127.0.0.1 - - [28/Oct/2016:18:35:05 -0400] "POST /graphql HTTP/1.1" 200 153340 "http://localhost:3006/playground" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "my_app"
```

That would be parsed by a regex like this:
```
(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<app_name>[^\"]*)")?
```

Example: [here](https://fluentular.herokuapp.com/parse?regexp=%28%3F%3Cremote%3E%5B%5E+%5D*%29+%28%3F%3Chost%3E%5B%5E+%5D*%29+%28%3F%3Cuser%3E%5B%5E+%5D*%29+%5C%5B%28%3F%3Ctime%3E%5B%5E%5C%5D%5D*%29%5C%5D+%22%28%3F%3Cmethod%3E%5CS%2B%29%28%3F%3A+%2B%28%3F%3Cpath%3E%5B%5E%5C%22%5D*%29+%2B%5CS*%29%3F%22+%28%3F%3Ccode%3E%5B%5E+%5D*%29+%28%3F%3Csize%3E%5B%5E+%5D*%29%28%3F%3A+%22%28%3F%3Creferer%3E%5B%5E%5C%22%5D*%29%22+%22%28%3F%3Cagent%3E%5B%5E%5C%22%5D*%29%22+%22%28%3F%3Capp_name%3E%5B%5E%5C%22%5D*%29%22%29%3F&input=127.0.0.1+-+-+%5B28%2FOct%2F2016%3A18%3A35%3A05+-0400%5D+%22POST+%2Fgraphql+HTTP%2F1.1%22+200+153340+%22http%3A%2F%2Flocalhost%3A3006%2Fplayground%22+%22Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_12_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F74.0.3729.169+Safari%2F537.36%22+%22my_app%22&time_format=)

Thanks!

**Comment by lestrrat** [comment]
I hear you, but since this is a tool to work with [apache log formats](http://httpd.apache.org/docs/current/mod/mod_log_config.html#formats) and they don't have it, I don't think there's much chance in this library implementing that feature.

I can think of workarounds like using the server name as a hint and including that in the log, or maybe use one of the header values to encode this information via `%{header-name}o`, but ultimately adding custom fields was never part of the Apache log format.

When I see before hand that I want to add arbitrary fields, I go for structured logging a la [LTSV](http://ltsv.org/) or something like [zap](https://github.com/uber-go/zap) instead of Apache logging, as those formats allow you to be completely arbitrary about which fields to include in their logs

I'm going to close this for now, but if I'm mistaken about Apache not supporting custom fields, feel free to reopen.

**Comment by charlysan** [comment]
I understand. Thanks for the reply @lestrrat.

**Comment by charlysan** [comment]
Sorry for commenting on a closed issue @lestrrat, but I have just seen this:

![image](https://user-images.githubusercontent.com/12597670/60912615-269c9e00-a25c-11e9-993f-43996081b05d.png)

I think this will work perfectly for me. The service/app name could be set by the value of some  environment variable. I see that your library does not support that directive. Please let me know if I can add a PR with the code to support this. Thanks.

**Comment by lestrrat** [comment]
Oh, I hadn't implemented this, huh...

**Comment by lestrrat** [comment]
should be fixed now. Please open a new Issue if there's something wrong!

**Comment by charlysan** [comment]
Thanks, it looks good. Are you going to create a new release that includes the last merge?

**Comment by lestrrat** [comment]
Ah, wasn't in a hurry to do that, but I suppose I should. Just to make sure, did you actually trying running the env var stuff at your end? I just want another set of eyes over it.

**Comment by charlysan** [comment]
Let me check...

**Comment by charlysan** [comment]
I've just pulled the latest changes from master and tried it out using the following string format:

```
`%h %v %u %t "%r" %>s %b "%{MY_VAR}e" "%{Referer}i" "%{User-agent}i"`
```

Without `MY_VAR`:
```
$ env  LOGGER_REQUESTS=true go run cmd/app/main.go
2019/07/09 23:12:56 Main : Started : Application Initializing
[::1] localhost - [09/Jul/2019:23:13:01 -0300] "POST /graphql HTTP/1.1" 200 32 "-" "-" "insomnia/6.4.2"
```

With `MY_VAR`:
```
$ env MY_VAR=my_service LOGGER_REQUESTS=true go run cmd/app/main.go
2019/07/09 23:13:23 Main : Started : Application Initializing
[::1] localhost - [09/Jul/2019:23:13:26 -0300] "POST /graphql HTTP/1.1" 200 32 "my_service" "-" "insomnia/6.4.2"
```

It works as expected.

**Comment by lestrrat** [comment]
Cool.

Voila: https://github.com/lestrrat-go/apache-logformat/releases/tag/v2.0.3

Thanks for the prodding!
