### ISSUE TITLE
Broken releases, unable to update module in projects.

### ISSUE THREAD

**Issue by davidnewhall** [lestrrat-go/apache-logformat#27]
The v2 releases do not conform to the go.mod standard. You must release them with a `/v2` signature.  Here's some light reading to get you acquainted: https://blog.golang.org/v2-go-modules

```
$ go get -u github.com/lestrrat-go/apache-logformat@v2.0.5
go get github.com/lestrrat-go/apache-logformat@v2.0.5: github.com/lestrrat-go/apache-logformat@v2.0.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Love your module, but I want to use `%{ms}T` and I cannot get v2.0.5. :(

EDIT: For anyone else trying to use the latest code, this worked:
```
$ go get -u github.com/lestrrat-go/apache-logformat@master
```

**Comment by lestrrat** [comment]
Yes, I know. I personally hated the `/v2` bit, and I wished that the Go team would some day change their ways while I just pretend like this worked, but I guess Go 1.16(beta) with its changed `go mod tidy` came, eh...

Thanks for using this module, and I will eventually get to it, but it isn't at the top of my list. If you could spare some time to create a PR that does the git mv bit, I'd much appreciate it.

**Comment by davidnewhall** [comment]
This affects all versions of Go... I'm on 1.15. I don't have any v2 modules myself, I just avoid it personally haha. If I find some time I'll try to submit a PR. It's just challenging to test.

**Comment by lestrrat** [comment]
Hmm, never had a single problem so far with this until I upgraded to go 1.16beta1, but I admit I was trying very hard not to look at this problem, so I'm willing to accept I had been blind.
