### ISSUE TITLE
Expose internal methods, or Redact sensitive data from logs

### ISSUE THREAD

**Issue by davidnewhall** [lestrrat-go/apache-logformat#29]
Any chance you can move `logctx` and `httputil` out of the `internal/` folder and into a `pkg/` folder? This will allow me to write my own `Wrap()` procedure. 

The above is a possible solution to my problem. To avoid the [XY Problem](https://xyproblem.info), this is my actual issue:

I want to hide sensitive data from logs. Some requests have keys and token in the parameters. I want to redact those before logging them to a file. I feel like this should be very easy if I build the Wrap() method into my own app.

Any ideas or thoughts are appreciated! Thanks!

**Comment by lestrrat** [comment]
I'm going assume you want to redact this info from the headers.

```go
r.Heade

**Comment by lestrrat** [comment]
I was going to write something up, but I think I'm missing the context. Can you be more specific as to what you want to do.

At the moment I don't feel like internal bit belongs to the public API, but I could be wrong. I think I need a more info

**Comment by davidnewhall** [comment]
Sure! I'm basically trying to do this (see following code) before the logger runs. The problem seems to be the logger grabs the request URI before I have a chance to modify it, and I'm just not sure how to get around that. I looked at the Wrap function and it seems like I could add this code right into it, but all the procedures it calls are internal packages.

```
func (c *Client) stripSecrets(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)

		secretKey := "something-secret"

		r.RequestURI = strings.ReplaceAll(r.RequestURI, secretKey, "<redacted>")
	})
}
```

This is just an example and probably isn't the right way to approach this. My other thought was to make an outbound header with the cleaned version of the request URI and log that instead of `%r`. I'm not keen on adding random headers just to write logs though (which I'm unfortunately already doing for another value).

It's entirely possible I'm just daft, and missing an existing feature to log "random values" (that are not headers). I could certainly store the cleaned version of the URI in another variable and log that somehow instead of `%r`. Is that possible?

**Comment by lestrrat** [comment]
I'm not sure why you are calling `next.ServeHTTP()` first, and THEN removing the information...?

```go
  next.ServeHTTP(w, r) // apachelog stuff runs here
  // And you're redacting sensitive information afterwards...?
  secretKey := "something-secret"
  r.RequestURI = strings.ReplaceAll(r.RequestURI, secretKey, "<redacted>")
```

I don't know how exactly you are going to use it, but the following pseudocode would be in line with what I would probably do.

```go
func YourHandler(w http.ResponseWriter, r *http.Request) { }
func Wrap(h http.Handler), al *apachelog.ApacheLog) http.Handler {
   h = al.Wrap(h)
   return func(w http.ResponseWraier, r *http.Request) {
       // redact stuff
       ...
      return h.ServeHTTP(w, r)
   }
}

http.Handle('/', Wrap(YourHandler, apachelog.CombinedLog)
```

**Comment by davidnewhall** [comment]
> I'm not sure why you are calling next.ServeHTTP() first, and THEN removing the information...?

It was just an example. I've been trying a number of things. :) The way I had this method ordered in the chain I felt like this would work. The logger was calling this method, and this method calls the downstream method that does actual request handling. 

Let me play with your example.. thank you!

**Comment by lestrrat** [comment]
> The logger was calling this method, and this method calls the downstream method that does actual request handling.

I'm only guessing, but if I understand you correctly, you _probably_ have this wrong. The handler that strips the sensitive data must call the main http.Handler that has been wrapped with apachelog.ApacheLog

**Comment by davidnewhall** [comment]
I guess I'm just not sure how to redact the secret from the logger but not the application.  I don't actually think I have any way to directly overwrite the requestURI that's being logged with `%r`.

 I did solve my problem using a header. It's at least an incoming header, which is fine for this purpose since it's basically ignored. Here's the diff in my app that solves my issue: https://github.com/Notifiarr/notifiarr/pull/51/commits/4a07abfbc1ddec8652d623879edd96bce1c124eb

Thank you for your help! It got my out of order handlers fixed!
