### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by davidnewhall** [lestrrat-go/apache-logformat#31]
Hello! I'm back :)

I've been using this library a really long time and I've never had a problem. Lately I've been adding a GUI to my app where it used to just be simple API calls. I got this panic on day 2 of development.  I'm not quite sure what to make of it, I'm not sure how prolific it is, and I don't know if I can reproduce it, but I wanted to share it with you in case you had some ideas. It seems to generate within this library, but I'm willing tp be wrong on that.

Not that I expect you to dig in my code, but just in case you have questions, this is the commit where the panic occurred. https://github.com/Notifiarr/notifiarr/commit/c3ba9c5cfda305d7dec6ca739790f5c0a5d48112

I'll definitely let you know if I see it happening again. Thanks!

```
[ERROR] 2022/01/25 19:08:50 http: panic serving [::1]:54074: bytes.Buffer.WriteTo: invalid Write count
goroutine 3488 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/server.go:1801 +0xb9
panic({0x48aa6c0, 0x4ac89a0})
	/usr/local/Cellar/go/1.17.3/libexec/src/runtime/panic.go:1047 +0x266
bytes.(*Buffer).WriteTo(0xc000ca2450, {0x4ade7e0, 0xc000262120})
	/usr/local/Cellar/go/1.17.3/libexec/src/bytes/buffer.go:241 +0x106
github.com/lestrrat-go/apache-logformat.(*ApacheLog).WriteLog(0xc000011020, {0x4ade7e0, 0xc000262120}, {0x4afcef0, 0xc000c2a060})
	/Users/david/go/pkg/mod/github.com/lestrrat-go/apache-logformat@v0.0.0-20200929122403-cd9b7dc018c7/logformat.go:40 +0x13c
github.com/lestrrat-go/apache-logformat.(*ApacheLog).Wrap.func1.1()
	/Users/david/go/pkg/mod/github.com/lestrrat-go/apache-logformat@v0.0.0-20200929122403-cd9b7dc018c7/logformat.go:58 +0x65
github.com/lestrrat-go/apache-logformat.(*ApacheLog).Wrap.func1({0x4aedbb8, 0xc00061e9a0}, 0xc000154160)
	/Users/david/go/pkg/mod/github.com/lestrrat-go/apache-logformat@v0.0.0-20200929122403-cd9b7dc018c7/logformat.go:66 +0x1e2
net/http.HandlerFunc.ServeHTTP(0x4925e40, {0x4aedbb8, 0xc00061e9a0}, 0xe)
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x2f
github.com/Notifiarr/notifiarr/pkg/client.(*Client).stripSecrets.func1({0x4aedbb8, 0xc00061e9a0}, 0xc000207100)
	/Users/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers.go:137 +0x15d
net/http.HandlerFunc.ServeHTTP(0x0, {0x4aedbb8, 0xc00061e9a0}, 0x406332e)
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc000ca37d0}, {0x4aedbb8, 0xc00061e9a0}, 0xc000207100)
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0009ba500, {0x4af22d0, 0xc0009c0180})
	/usr/local/Cellar/go/1.17.3/libexec/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
```

**Comment by lestrrat** [comment]
Interesting. The error message indicates that it's coming from `bytes.Buffer`. This is from go 1.17.6, but I suspect it's the same

https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/bytes/buffer.go;l=241

The error occurs when nBytes, which is the length of data in the write source (bytes.Buffer from apache-logformat) is _LESS_ than the actual number of bytes reported to be written by the write destination, in your case is `c.Logger.HTTPLog.Writer()`. So the logger must think that it wrote more than it was asked to.

Writer is an instance of `io.Writer` from `log` package... Hmm.

If there's a bug in my code, it would have to be somewhere in the interaction with the logger, But I'm not sure. I think it would be best if you sprinkle a few debug prints around `bytes.Buffer.WriteTo` and maybe print out what it was intending to write, how many bytes you were expecting to write, and how many bytes the destination reported it wrote.

**Comment by davidnewhall** [comment]
kk, let me see what I can do! Thanks for the pointers! fwiw, my other dev got the panic too, same stack trace, so it's something we may be able to narrow down.

**Comment by davidnewhall** [comment]
I think I found the bug in one of my libraries I'm surprised this is the first time I'm noticing it, but it's because requests are coming in much faster with the new interface. This channel should not be buffered: https://github.com/golift/rotatorr/blob/main/logger.go#L91

I'm surprised this module or code path doesn't show up in the stack trace, because bytes.Buffer is clearly calling the `Write` method in this library. Thanks again for the pointer, it made me go sleuth the code down more.

**Comment by lestrrat** [comment]
Np. glad to be of help.

incidentally I think I see the bug.

you log library has a subtle timing issue.
Namely, you can't assert that l.resp will retuen the result from the write that you sent to l.log.

for example, this could happen

```go
l.log<-req1
l.log<-req2
res1:= <-l.res
res2 := <-l.res
```

depending on when the channel receive happes, you might get the result from a previous write. this is consistent with the panic.

to avoid this you need to send a custom cahnnel for the operation.

 
 ​```go
ch:=make(chan res)
backend.cmds<-cmd{replyCh: ch}
res:=<-ch
```

**Comment by davidnewhall** [comment]
I totally appreciate you checking out my code and providing some feedback. In your sample, it should cause a deadlock at `l.log<-req2` because the channel is (now) non-buffered and still processing `l.log<-req1` (until the result is read). This may demonstrate that behavior: https://go.dev/play/p/qLjlEgoHJzW - removing line 16 makes it work as expected.

**Comment by lestrrat** [comment]
Ah, true true. You are absolutely right. I somehow just assumed a buffer on the channel. My bad.

**Comment by davidnewhall** [comment]
The buffer was my bug. I provided a crappy link that shows after I fixed it. That 1 channel had a buffer of 1. I have no idea why I did that..

**Comment by davidnewhall** [comment]
Love your module and your customer service! Keep up the great work and good attitude! <3
